/**
 * One-time setup: creates .env with SESSION_SECRET and ADMIN_PASSWORD_HASH.
 * Run: node scripts/setup-env.js "YourSecurePassword"
 * If you omit the password, "changeme" is used (change it after first login).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');

const password = process.argv[2] || 'changeme';
const envPath = path.join(__dirname, '..', '.env');

const SESSION_SECRET = crypto.randomBytes(32).toString('hex');
const ADMIN_PASSWORD_HASH = bcrypt.hashSync(password, 10);

const content = `# Admin panel (required when running server.js)
# Generated by node scripts/setup-env.js
ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
SESSION_SECRET=${SESSION_SECRET}
`;

fs.writeFileSync(envPath, content, 'utf8');
console.log('.env created successfully.');
if (password === 'changeme') {
  console.log('Default password is "changeme". Run again with your own: node scripts/setup-env.js "YourPassword"');
} else {
  console.log('You can log in to admin with the password you provided.');
}
